In [90]:
!nvidia-smi

Mon Mar 27 20:59:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0    27W /  85W |    488MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 00. Pytorch fundamentals
### Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [91]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__
torch.cuda.is_available()

True

## Introduction to Tensors

### Creating tensors  https://pytorch.org/docs/stable/tensors.html

In [92]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [93]:
scalar.ndim

0

In [94]:
# Get tensor back as python int
scalar.item()

7

In [95]:
# Vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [96]:
vector.ndim

1

In [97]:
vector.shape

torch.Size([2])

In [98]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [99]:
MATRIX.ndim

2

In [100]:
MATRIX.shape

torch.Size([2, 2])

In [101]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 8],
                        [7, 8, 0]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 8],
         [7, 8, 0]]])

In [102]:
TENSOR.ndim

3

In [103]:
TENSOR.shape

torch.Size([1, 3, 3])

In [104]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 8],
        [7, 8, 0]])

### Random tensors

Why random tensors?

Random tensors are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update again`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [105]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0874, 0.1941, 0.7794, 0.0985],
        [0.8375, 0.0771, 0.6953, 0.7047],
        [0.6143, 0.3753, 0.5365, 0.3055]])

In [106]:
random_tensor.ndim

2

In [107]:
random_tensor.shape

torch.Size([3, 4])

In [108]:
# Create random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color Channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [109]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [110]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [111]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)

### Tensor datatypes
**NOTE**: Tensor datatypes is one of 3 big erroes you'll run into with PyTorch & Deep Learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [113]:
## Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, 
                                device=None, # 'cuda' or 'cpu' What device to store the tensor on
                                requires_grad=False) # Whether or or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [114]:
float_32_tensor.dtype

torch.float32

In [117]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [119]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [120]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensor not right datatype - to get datatype from a tensor, can use  `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use  `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use  `tensor.device`



In [121]:
# Create a tensor of random floats
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6952, 0.0911, 0.5891, 0.3923],
        [0.1971, 0.0205, 0.3045, 0.1363],
        [0.8987, 0.8834, 0.5917, 0.8836]])

In [123]:
# Find details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6952, 0.0911, 0.5891, 0.3923],
        [0.1971, 0.0205, 0.3045, 0.1363],
        [0.8987, 0.8834, 0.5917, 0.8836]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [125]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [126]:
# Create a tensor and multiply 10 to it
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [127]:
# Create a tensor and subtract 10 to it
tensor = torch.tensor([1, 2, 3])
tensor - 10

tensor([-9, -8, -7])

In [128]:
# Try out PyTorch built-in tensor operations
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More info on matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

torch.Size([3, 2])

In [129]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals; {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals; tensor([1, 4, 9])


In [135]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [132]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.67 ms, sys: 277 µs, total: 1.94 ms
Wall time: 1.84 ms


In [136]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 116 µs, sys: 48 µs, total: 164 µs
Wall time: 116 µs


tensor(14)

## One of the most common errors in deep learing are `Shape errors` 

In [138]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [139]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors unsing transpose

A **transpose** swithces the axes or dimebnsions of given tensor

In [141]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [142]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [146]:
print(torch.mm(tensor_A, tensor_B.T))
print(torch.mm(tensor_A.T, tensor_B))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 76, 103],
        [100, 136]])
