In [55]:
!nvidia-smi

Tue Mar 28 19:37:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8    15W /  80W |      6MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 00. Pytorch fundamentals
### Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [56]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

torch.__version__
torch.cuda.is_available()

True

## Introduction to Tensors

### Creating tensors  https://pytorch.org/docs/stable/tensors.html

In [57]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [58]:
scalar.ndim

0

In [59]:
# Get tensor back as python int
scalar.item()

7

In [60]:
# Vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [61]:
vector.ndim

1

In [62]:
vector.shape

torch.Size([2])

In [63]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [64]:
MATRIX.ndim

2

In [65]:
MATRIX.shape

torch.Size([2, 2])

In [66]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 8],
                        [7, 8, 0]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 8],
         [7, 8, 0]]])

In [67]:
TENSOR.ndim

3

In [68]:
TENSOR.shape

torch.Size([1, 3, 3])

In [69]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 8],
        [7, 8, 0]])

### Random tensors

Why random tensors?

Random tensors are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update again`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [70]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1010, 0.7356, 0.2973, 0.2192],
        [0.8950, 0.2873, 0.4906, 0.6406],
        [0.6866, 0.0803, 0.7149, 0.4921]])

In [71]:
random_tensor.ndim

2

In [72]:
random_tensor.shape

torch.Size([3, 4])

In [73]:
# Create random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color Channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [74]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [76]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)

### Tensor datatypes
**NOTE**: Tensor datatypes is one of 3 big erroes you'll run into with PyTorch & Deep Learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [78]:
## Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, 
                                device=None, # 'cuda' or 'cpu' What device to store the tensor on
                                requires_grad=False) # Whether or or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [79]:
float_32_tensor.dtype

torch.float32

In [80]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [82]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensor not right datatype - to get datatype from a tensor, can use  `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use  `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, can use  `tensor.device`



In [83]:
# Create a tensor of random floats
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4012, 0.1924, 0.7694, 0.7779],
        [0.6417, 0.0603, 0.7880, 0.6398],
        [0.7382, 0.5196, 0.9340, 0.7948]])

In [84]:
# Find details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.4012, 0.1924, 0.7694, 0.7779],
        [0.6417, 0.0603, 0.7880, 0.6398],
        [0.7382, 0.5196, 0.9340, 0.7948]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [85]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [86]:
# Create a tensor and multiply 10 to it
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [87]:
# Create a tensor and subtract 10 to it
tensor = torch.tensor([1, 2, 3])
tensor - 10

tensor([-9, -8, -7])

In [88]:
# Try out PyTorch built-in tensor operations
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More info on matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [89]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals; {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals; tensor([1, 4, 9])


In [90]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [91]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.32 ms, sys: 1.7 ms, total: 4.02 ms
Wall time: 2.66 ms


In [92]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 641 µs, total: 641 µs
Wall time: 525 µs


tensor(14)

## One of the most common errors in deep learing are `Shape errors` 

In [93]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [100]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors unsing transpose

A **transpose** swithces the axes or dimebnsions of given tensor

In [101]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [102]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [103]:
print(torch.mm(tensor_A, tensor_B.T))
print(torch.mm(tensor_A.T, tensor_B))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 76, 103],
        [100, 136]])


## Finding the min, masx, mean, sum etc (tensor aggregation)

In [94]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [95]:
torch.min(x), x.min(), torch.max(x), x.max()

(tensor(1), tensor(1), tensor(91), tensor(91))

In [96]:
# NOTE: torch.mean() need float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [97]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding positional max and min

In [98]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

In [99]:
x[9], x[0]

(tensor(91), tensor(1))

# Reshaping, Stacking, Squeezing, Un-squeezing tensors

* **Reshaping** - reshapes an input tensor to defined shape
* **View** - Return a view of input tensor of certain shape but keep the same memory as the original tensor
* **Stacking**- combine multiple tensor on top of each other (vstack) or next to each other (hstack)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - adds a `1` dimensionat to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [116]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [121]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [122]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [119]:
y = torch.arange(0., 12.)
y, y.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]))

In [120]:
# Add an extra dimension
y_reshaped = y.reshape(3, 4)
y_reshaped, y_reshaped.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [124]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [125]:
# Changing z changes x (because they share the same memory)
z[:, 0] = 111
z, x

(tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [128]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[111., 111., 111., 111.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.]])

In [133]:
# torch.squeeze() removes all single dimensions
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"Squeezed tensor: {x_squeezed}")
print(f"Squeezed tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])
Previous tensor shape: torch.Size([1, 9])
Squeezed tensor: tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
Squeezed tensor shape: torch.Size([9])


In [130]:
x_reshaped.shape

torch.Size([1, 9])

In [132]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 torch.Size([9]))

In [136]:
# torch.unsqueeze() adds a dimension of size 1 at a specified dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous tensor shape: {x_squeezed.shape}")

# Add extra dimension with unsqeeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Unsqueezed tensor: {x_unsqueezed}")
print(f"Unsqueezed tensor shape: {x_unsqueezed.shape}")

Previous tensor: tensor([111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
Previous tensor shape: torch.Size([9])
Unsqueezed tensor: tensor([[111.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])
Unsqueezed tensor shape: torch.Size([1, 9])


In [150]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [Height, Width, Color Channels]
x_original, x_original.size()

(tensor([[[0.8233, 0.7645, 0.9607],
          [0.1222, 0.7314, 0.9554],
          [0.8367, 0.1615, 0.9010],
          ...,
          [0.7151, 0.7976, 0.1847],
          [0.1275, 0.7045, 0.3418],
          [0.7829, 0.3902, 0.6001]],
 
         [[0.1152, 0.0611, 0.0760],
          [0.4610, 0.6193, 0.5085],
          [0.8872, 0.7801, 0.1459],
          ...,
          [0.1707, 0.5523, 0.4306],
          [0.8443, 0.8051, 0.4310],
          [0.5417, 0.2418, 0.9113]],
 
         [[0.1395, 0.8402, 0.1198],
          [0.2781, 0.5497, 0.4468],
          [0.8060, 0.1771, 0.1840],
          ...,
          [0.9141, 0.9875, 0.2756],
          [0.0043, 0.1118, 0.6318],
          [0.3013, 0.6258, 0.7757]],
 
         ...,
 
         [[0.0074, 0.5851, 0.4633],
          [0.4744, 0.0405, 0.6831],
          [0.9828, 0.8464, 0.8791],
          ...,
          [0.5909, 0.3840, 0.7321],
          [0.2629, 0.6835, 0.4271],
          [0.9144, 0.4522, 0.2336]],
 
         [[0.7208, 0.6431, 0.8396],
          [0

In [152]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # [Color Channels, Height, Width]
x_permuted, x_permuted.size()

(tensor([[[0.8233, 0.1222, 0.8367,  ..., 0.7151, 0.1275, 0.7829],
          [0.1152, 0.4610, 0.8872,  ..., 0.1707, 0.8443, 0.5417],
          [0.1395, 0.2781, 0.8060,  ..., 0.9141, 0.0043, 0.3013],
          ...,
          [0.0074, 0.4744, 0.9828,  ..., 0.5909, 0.2629, 0.9144],
          [0.7208, 0.3263, 0.2895,  ..., 0.0140, 0.1034, 0.6906],
          [0.2033, 0.2563, 0.2993,  ..., 0.5628, 0.5575, 0.7387]],
 
         [[0.7645, 0.7314, 0.1615,  ..., 0.7976, 0.7045, 0.3902],
          [0.0611, 0.6193, 0.7801,  ..., 0.5523, 0.8051, 0.2418],
          [0.8402, 0.5497, 0.1771,  ..., 0.9875, 0.1118, 0.6258],
          ...,
          [0.5851, 0.0405, 0.8464,  ..., 0.3840, 0.6835, 0.4522],
          [0.6431, 0.7811, 0.1087,  ..., 0.1124, 0.0207, 0.2039],
          [0.2562, 0.8298, 0.1358,  ..., 0.9409, 0.1278, 0.9264]],
 
         [[0.9607, 0.9554, 0.9010,  ..., 0.1847, 0.3418, 0.6001],
          [0.0760, 0.5085, 0.1459,  ..., 0.4306, 0.4310, 0.9113],
          [0.1198, 0.4468, 0.1840,  ...,

In [153]:
x_original[0, 0, 0] = 420
x_permuted[0, 0, 0]

tensor(420.)

## Indexing tensors (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [157]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [166]:
# Let's index our new tensor
print(x[0])
print(x[0][0], x[0, 0])
print(x[0, 2, 2], x[0][2][2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3]) tensor([1, 2, 3])
tensor(9) tensor(9)


In [167]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [168]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [171]:
# Get all values of the 0 dim but only the index value of 1st and 2nd dimension
x[0, 1:3, 1]

tensor([5, 8])

In [172]:
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy
NumPy is a popular Python library for scientific computing. It's used for a lot of things, including data manipulation and data analysis.

And because of this, PyTorch ha a functionality to interact with NumPy.

* Data in NumPy, want PyToch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor, want NumPy -> `torch.Tensor.numpy()`

In [173]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [175]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations-> update random numbers and try to make them a better representation of the data -> again -> again -> ...`

To reduce the randomness, we can set the **random seed**.

https://pytorch.org/docs/stable/notes/randomness.html

In [187]:
random_tensor_A = torch.rand(size=(3, 4))
random_tensor_B = torch.rand(size=(3, 4))

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3004, 0.6940, 0.7943, 0.2293],
        [0.4452, 0.3734, 0.6052, 0.4937],
        [0.1797, 0.3787, 0.9356, 0.0090]])
tensor([[0.4873, 0.2238, 0.2397, 0.6064],
        [0.0146, 0.3717, 0.7566, 0.6639],
        [0.5121, 0.1724, 0.3274, 0.7429]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [190]:
# Let's make some random but reproducible tensors
import torch
# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch objects on the GPU

In [191]:
!nvidia-smi

Tue Mar 28 21:49:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8    15W /  80W |      6MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [192]:
### Let's check if we have a GPU available
if torch.cuda.is_available():
    print("GPU available")

GPU available


In [196]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

## 3. Putting tensor (and models) on the GPU

In [199]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor, tensor.device

tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3, 4, 5], device='cuda:0'), device(type='cuda', index=0))

## 4. Moving tensors back on the CPU

In [201]:
# If tensor is on a GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [202]:
# To fix GPU tensor with NumPy issue, we can first st it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4, 5])

## Excercises & Extra Curriculum