# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [21]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x, x.shape

(tensor([[0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883],
         [0.0500, 0.4663, 0.9397, 0.2961, 0.9515, 0.6811, 0.0488],
         [0.8163, 0.4423, 0.2768, 0.8998, 0.0960, 0.5537, 0.3953],
         [0.8571, 0.6396, 0.7403, 0.6766, 0.3798, 0.3948, 0.0880],
         [0.7709, 0.8970, 0.8421, 0.1473, 0.5223, 0.1475, 0.2248],
         [0.2086, 0.6709, 0.2020, 0.4891, 0.5210, 0.8223, 0.1220],
         [0.1567, 0.2097, 0.8500, 0.3203, 0.9217, 0.6808, 0.5633]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [22]:
# Create another random tensor
y = torch.rand(1, 7)
print(y, y.shape)
# Perform matrix multiplication 
z = torch.mm(x, y.T)
z


tensor([[0.4963, 0.4012, 0.5627, 0.3858, 0.4965, 0.5638, 0.1089]]) torch.Size([1, 7])


tensor([[0.9014],
        [1.7166],
        [1.4883],
        [1.7803],
        [1.6401],
        [1.4107],
        [1.6666]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [23]:
# Set manual seed
MANUAL_SEED = 0
torch.manual_seed(MANUAL_SEED)


# Create two random tensors
a = torch.rand(7, 7)
b = torch.rand(1, 7)
# Matrix multiply tensors
c = a @ b.T
c

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [32]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
k = torch.rand(2, 3).to('cuda')
l = torch.rand(size=(2,3) , device='cuda')
print(k, k.shape)
print(l, l.shape)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') torch.Size([2, 3])
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') torch.Size([2, 3])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
m = k @ l.T
m

tensor([[0.4733, 0.3815],
        [0.4754, 0.9401]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [37]:
# Find max
print(m.max())
# Find min
print(m.min())


tensor(0.9401, device='cuda:0')
tensor(0.3815, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [39]:
# Find arg max
print(m.argmax())

# Find arg min
print(m.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [44]:
# Set seed
torch.manual_seed(7)

# Create random tensor
p = torch.rand(1, 1, 1, 10)

# Remove single dimensions
q = p.squeeze()

# Print out tensors and their shapes
print(p, p.shape)
print(q, q.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
